// <auto-generated />
namespace Masticore.Infrastructure.Azure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4PolicyInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4PolicyInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201908130014246_4-PolicyInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
